[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
python = "*"
ipykernel = "*"
pandas = "*"
polars = "*"
pyarrow = "*"
seaborn = "*"
scikit-learn = "*"
tqdm = "*"
ipywidgets = "*"

[tasks.to_parquet]
cmd = "python data_preparation/to_parquet.py"
inputs = ["data_preparation/to_parquet.py"]
outputs = ["data/*.parquet"]

[tasks.to_wide]
cmd = "python data_preparation/to_wide.py"
inputs = ["data_preparation/to_wide.py"]
outputs = ["data/wide.parquet"]

[tasks.expand_test_features]
cmd = "python data_preparation/expand_test_features.py"
inputs = ["data_preparation/expand_test_features.py", "data/*.parquet"]
outputs = ["data/ids_test_expanded.parquet"]
