[project]
name = "florcitas"
version = "0.0.1"

[build-system]
requires = ["uv_build>=0.8,<0.9.0"]
build-backend = "uv_build"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]
